version: "3.9"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - /Obsidian:/app/notes

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8882:443"
    volumes:
      - ./frontend:/srv # For live updates during dev
      - ./ssl:/ssl # Certificates
    depends_on:
      - backend
