version: "3.9"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - /path/to/your/notes:/app/notes
    networks:
      - app-network
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8082:80"
    depends_on:
      - backend
    networks:
      - app-network
networks:
  app-network:
